### ISSUE TITLE
Clarify README 

### ISSUE THREAD

**Issue by rhagarty** [IBM/kafka-streaming#1]
@ScrapCodes - good start, but here are some questions/issues I have regarding the README.

Abstract
- Replace title with a description of this journey. Something like "Clickstream Analysis using Apache Spark and Kafka".
- Combine "In this journey" paragraphs into one. I think you should start with the second one. 
- Can you elaborate on the "Few Business ..." bullets? Not sure what what they mean or how they are related or solved by this journey.

Setup instructions
- The first paragraph is confusing, specifically the part concerning the external publisher. Is the user required to do something here? What is the downloaded data used for?

**Comment by ScrapCodes** [comment]
@rhagarty Thanks for the kind review. Please take a look at the updates.

**Comment by rhagarty** [comment]
@ScrapCodes - very nice update. In the future, please submit changes using pull requests. It makes it easier to review and track changes.

**Comment by ScrapCodes** [comment]
@rhagarty, Thanks that makes sense.
