### ISSUE TITLE
Error running locally

### ISSUE THREAD

**Issue by rhagarty** [IBM/kafka-streaming#10]
rhagarty@Richs-MBP-15 kafka-1.0.0-src $ tail -200 ~/Downloads/2017_01_en_clickstream.tsv | KAFKA_OPTS="-Djava.security.auth.login.config=config/jaas.conf" bin/kafka-console-producer.sh --broker-list ip:port  --topic clicks --producer.config=config/producer.properties
Classpath is empty. Please build the project first e.g. by running './gradlew jar -Pscala_version=2.11.11'

**Comment by xwu0226** [comment]
@rhagarty Thanks! @ScrapCodes

**Comment by ScrapCodes** [comment]
@rhagarty You need to either download a binary distribution or in case you download a source distribution, you need to build it - as the error message is indicating. 

How do you want this to be documented?
