### ISSUE TITLE
Clarify and cleanup instructions for running locally

### ISSUE THREAD

**Issue by rhagarty** [IBM/kafka-streaming#14]
Setup clickstream
* Step 1 - specify exact file that needs to be downloaded from Wikipedia Clickstream data, or modify the tail command to be more generic (it specifies '2017_01_en_clickstream.tsv').
* Step 2 - provide more detail on why I would want to create a local kafka service. Is this related to downloading Apache Kafka earlier? If I want to use the IBM Message Hub, how would I do that? Is there a fee involved? If so, maybe we shouldn't include this as an option?
* Step 3 - "a handy command line utility for this purpose" - what purpose is that?
* Step 3 - command has an "ip:port". What should I use here?

Run the script:
* commands should be single lineso that user can cut/paste in scala shell.
* commands should show expected output.
* what "ip:port" should I use?

**Comment by xwu0226** [comment]
@ScrapCodes Any update on this? Thanks!

**Comment by ScrapCodes** [comment]
User is supposed to :paste option, single line command will overflow.
