### ISSUE TITLE
Notebook issues

### ISSUE THREAD

**Issue by rhagarty** [IBM/kafka-streaming#15]
* please include more comments in the notebook cells. At a minimum, include the information from the README about the commands.
* When running, I get to 'cell [13]:  val query = messages.writeStream.outputMode("complete").option("truncate", "false").format("console").start()" and then the rest of the cells go blank. This has happened to me every time that I have run the notebook.

**Comment by xwu0226** [comment]
@ScrapCodes Any update on this? Thanks!

**Comment by ScrapCodes** [comment]
This issue seems to be transient, sometimes appears and then auto disappears.

**Comment by ScrapCodes** [comment]
@rhagarty Do you have an update, do you still see this?

**Comment by rhagarty** [comment]
@ScrapCodes did not see the disappearing cells problem, but still unable to stream data succesfully. Getting this error - 
[2017-12-10 23:31:14,405] ERROR Error when sending message to topic clicks with key: null, value: 40 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

**Comment by ScrapCodes** [comment]
This has something to do with Message Hub, I do get these errors at times, but messages get pushed. Fixing these problems requires access of the upstream kafka service(i.e. Message hub), it is unclear why you are getting timeouts for a correct address and setup. And if you are getting them, I am sure many others will do. Do you have a way forward?

**Comment by xwu0226** [comment]
@ScrapCodes I see only one existing pattern that uses MessageHub with Kafka, https://github.com/IBM/openwhisk-data-processing-message-hub

Can you see if you can find any reference or similarity here?

**Comment by rhagarty** [comment]
@ScrapCodes - it works for me now, but we need to add a couple instructions...
1) since the 'tail' command requires the clickstream tsv file be in '/data', we need to add the copying of the file to the list of commands.
2) I only got it to work by using the '/config/messagehub.properties' file, so we should probably add that a s a necessary step, instead of optional.
3) when importing the credentials into the notebook, the password value has 2 extra set of double quotes around it. This doesn't effect the running of the notebook, but when you copy this value to the messagehub.properties file, these must be removed. We either need to fix the import, or explicitly state to remove them when updating the properties file.

**Comment by ScrapCodes** [comment]
Thank you for the comments,
tail command does not have such a requirement, data can exist anywhere, and they just need to provide the correct path.

Rest of the comments, I will address in my pull request.

**Comment by ScrapCodes** [comment]
@rhagarty : Oops, I accidentally directly committed to master. But now, that it is done, feel free to send your correction.

**Comment by rhagarty** [comment]
@ScrapCodes - looks good
