### ISSUE TITLE
Add flow description for architecture diagram

### ISSUE THREAD

**Issue by rhagarty** [IBM/kafka-streaming#4]
See other Spark journeys for examples

**Comment by ScrapCodes** [comment]
Hi @rhagarty, please review following "Flow". To avoid code conflicts, I am awaiting the merge of your PR, before I can send a PR.

Flow

* A running instance of a clickstream, over a kafka or Message hub service.
* The Apache spark structured streaming job, reads the clickstream from specified topic on kafka/Message hub.
* The notebook can be directly loaded incase of IBM Datascience experience. Follow the read me for running it locally.
* The processed stream is printed to console using a Console Sink.
