### ISSUE TITLE
Editing the README

### ISSUE THREAD

**Issue by MadisonJMyers** [IBM/kafka-streaming#7]
@ScrapCodes great work! I have just a few notes which you can see below. Once you're finished implementing them, write me below and I'll close the issue.
 
- In the first section, “By determining the order in which a user clicks on a web site, what influenced him/her to a buying decision can be ascertained.” , is confusing. Reword. It may help to read it out loud. 
 - Same with: “Simillar to recommendation generation, by tracking user clicks across websites, users of websites are served more precisely targetted advertisement.”
 - “that gets highest number of user clicks.” Should be: “that gets the highest number of user clicks.”
 - In the paragraph below that, combination is spelled wrong.
 - Add periods to the end of all of your bullet points so that you stay consistent.
 - Under 2. Setup clickstream, the first two sentences should be one sentence with a comma in between. (“In case an existing clickstream is not available for processing, a simulating clickstream can be used.”
 - In the sentence right above the section “Run using a Jupiter notebook…” there’s a comma. This comma is not necessary so you can remove it.

**Comment by ScrapCodes** [comment]
Thank you for the review. You may review the edits [here](https://github.com/IBM/kafka-streaming/pull/8/commits/6fc8ff0dbed70c6c6be11ecb824d5668886f1bcd) .
